# Generated by Django 4.0.3 on 2022-03-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ad_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
